[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "DLHell"
version = "1.0"
dependencies = [
  "pefile",
  "impacket"
]
requires-python = ">=3.8"
authors = [
  {name = "kit", email = "kevin.tellier@synacktiv.com"}
]
maintainers = [
  {name = "kit", email = "kevin.tellier@synacktiv.com"}
]
description = "DLL Proxying & DCOM tricks"
readme = "README.md"
keywords = ["DLL Hijack", "DCOM"]

[project.urls]
Homepage = "https://synacktiv.com"
